server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/learning_plan?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    timeout: 2000ms
    database: 0
  
  # 邮件配置
  mail:
    host: smtp.qq.com
    port: 587
    username: 2872050303@qq.com
    password: hexoxjivhzrvdcjd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.learning.learning_habit_plan_backend.entity
  configuration:
    map-underscore-to-camel-case: true
